services:
  consumer2-real:
    build: .
    image: traffic/consumer2:latest
    container_name: consumer2-sign-classifier-real
    profiles:
      - real
    environment:
      USE_MOCK: "false"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_VHOST: /
      EXCHANGE_NAME: trabalho06.topic
      QUEUE_NAME: trabalho06.signs
      ROUTING_KEY: sign
    networks:
      - gerador-mensagens-ia-rabbitmq_trabalho06-net  
networks:
  gerador-mensagens-ia-rabbitmq_trabalho06-net:
    external: true 
